### ISSUE TITLE
Allow pull requests - Added expected HTTP code parameter

### ISSUE THREAD

**Issue by manuman94** [cec/wait-for-endpoint#4]
Hi!

Thank you for providing this awesome script, it is so useful for us.

I modified it in order to add a "expected code" parameter that allows the user to choose which HTTP status code the script has to wait.

Example of use:
./wait-for.sh https://domain.com/endpoint --code=404
or 
./wait-for.sh https://domain.com/endpoint -c 404

I tried to create a "Pull request" but it seems they are disabled. I get a 403 when I try to push my branch.

Is it ok to you to accept pull requests? Do you find this change useful?

Thank you, greetings.

**Comment by cec** [comment]
Hi @manuman94 I would gladly accept your pull request.

I think that in order to create a PR, you first need to fork this repository, push your commits to the fork and then open a PR from the fork to this repo.

Thank you :)

**Comment by manuman94** [comment]
Hi @cec!

Sorry, I never created a pull request at Github.

I created this pull request: https://github.com/cec/wait-for-endpoint/pull/5

Hope it helps.

Thank you!

**Comment by manuman94** [comment]
Fixed with pull request https://github.com/cec/wait-for-endpoint/pull/5 merged.

Closing the issue.
